config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :items, except: %i[show edit update] do
    get :uncategorized, on: :collection
  end
  devise_for :users
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :items, dependent: :destroy

  mount_uploader :icon, ImageUploader
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :items
  has_many :groups

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username image])
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username image])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[username image])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username image])
  end

  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all.order('name ASC')
  end

  # GET /groups/1 or /groups/1.json
  def show
    @user = User.find(current_user.id)
    @group = Group.find(params[:id])
    @items = current_user.items.where('group_id =?', @group).all.order('created_at DESC')
  end

  # GET /groups/new
  def new
    # @group = Group.new
    @group = current_user.groups.build
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to groups_path
    else
      redirect_to :new_group, notice: 'Invalid entry'
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def uncategorized
    @uncategorized = current_user.items.where(group_id: nil).all.order('created_at DESC')
    @amount_sum = current_user.items.sum(:amount)
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @group = current_user.groups.find_by(id: params[:id])
    redirect_to groups_path, notice: 'Not Authorized to edit this group' if @group.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.find(current_user.id)
  end

  def users
    @current_user = current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /items or /items.json
  def index
    @items = current_user.items.includes(:group).order('created_at DESC')
  end

  # GET /items/new
  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to items_path
    else
      redirect_to :new_item, notice: 'Invalid entry'
    end
  end

  def uncategorized
    @uncategorized = current_user.items.where(group_id: nil).all.order('created_at DESC')
    @items = Item.all
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @item = current_user.items.find_by(id: params[:id])
    redirect_to items_path, notice: 'Not Authorized to edit this Item' if @item.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :amount, :user_id, :group_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/groups/_form.html.erb
<div class="container text-center mt-3">
  <%= form_with(model: group) do |form| %>
    <% if group.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block", class:"form-label" %>
      <%= form.text_field :name, required: true, class:"form-control" %>
    </div>

    <div class="mt-4">
      <%= form.label :icon, style: "display: block", class:"form-label" %>
      <%= form.file_field :icon, required: true, class:"form-control" %>
    </div>

      <div class="mt-4">
      <%= form.number_field :user_id, id: :group_user_id, value: current_user.id, type: :hidden, class:"form-control" %>
      </div>

    <div class="mt-4">
      <%= form.submit "Add Group", required: true, class:"btn btn-custom p-3 mt-3" %>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<%= render 'header/nav' %>
<div class="container my-3 ">
<h1 class="text-center my-3"> Catalogued Books</h1>

<div id="groups" class="mb-5 pb-5">
  <% @groups.each do |group| %>

  <div class="card mb-4">
    <div class="card-body row align-items-center">
      <div class="d-flex col-9">
      
      <div class="card-text ">
      <%= image_tag group.icon_url.to_s, class:"img-fluid p-1 border border-2 item-icon", style:"height:120px; width:120px;" %>
      </div>
         
        <p class="px-3 p-md-3 align-self-center">
        <strong class="d-block mb-4 mb-md-5"> <%= link_to group.name, group, class:"capitalize"%> </strong>
        <strong class="d-block"><%= group.created_at.strftime("%d %b %Y") %> </strong>
        </p>
      </div>

      <div class="col-3 text-end">
        
        <%= button_to "Delete", group, method: :delete, class:"btn btn-primary" %>
      </div>
  
    </div>
  </div>
  <% end %>
  
    <hr />
    <hr />
    <h3>Numers of Item: <%= @groups.count %></h3>
</div>


<div class="text-center fixed-bottom pt-2 pb-3 bg-light">
<%= link_to "New group", new_group_path, class:"btn btn-custom w-75 fs-3 mx-auto text-white" %>
</div>
</div>

app/views/groups/new.html.erb
<%= render 'header/nav' %>
<h3 class="container mt-2 text-center mt-5">New Group</h3>
<%= render "form", group: @group %>

<br>

<div class="text-center">
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<%= render 'header/nav' %>
<div class="container my-3">
    <div class="">
      <% running_total = 0 %>
        <% @items.includes([:group]).each do |item| %>
          <div class="card mb-4">
            <div class="card-body row align-items-center"">
                <div class="d-flex col-9 ">
                      <% if item.group_id %>
                      <%= image_tag item.group.icon_url, class:"img-fluid p-1 border border-2 item-icon" %>
                      <% else %>
                      <img src="https://via.placeholder.com/100" alt="icon" class="border border-1 item-icon "> 
                      <% end %>
                    <p class="px-3 p-md-3 align-xself-center">
                      <strong class="d-block mb-3 mb-md-3 capitalize"> <%= item.name %> </strong>
                      <% if item.user_id %>
                      <strong class="d-block mb-3 mb-md-3 capitalize"> Author: <%= @user.username %> </strong>
                      <% end %>
                      <strong class="d-block"><%= item.created_at.strftime("%d %b %Y") %> </strong>        
                    </p>
                </div>
                <div class="col-3 text-end">
                  <p class="card-text  mb-4"><%= number_to_currency(item.amount) %></p>
                  <%= button_to "Delete", item, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
                </div>
            </div>
      <% running_total = running_total + (item.amount) %>
          </div>
          <% end %>
    </div>
    <hr />
    <hr />
    <hr />
    <h3>Total Amount: <%= @amount_sum %> <%= number_to_currency(running_total) %></h3>
    <h3>Numers of Item: <%= @items.count %></h3>
    <%= link_to "Back to Groups", groups_path, class:"btn btn-outline-info" %> | 
    <%= button_to "Delete Group", @group, method: :delete, class:"btn btn-outline-danger d-inline" %>
</div>

app/views/header/_nav.html.erb
<header class="nav-bar p-2 sticky-top">

<div class="d-flex justify-content-around py-4">
<%= link_to root_path do %>
<b class="nav-icon text-white"> &#9776; </b>
 <% end %>
<b class="nav-text text-uppercase fs-1 float-none"> Book Store </b>

<b class="nav-icon" id="navbarText" >  &#x2315; </b>

</div> 

<div class="d-flex justify-content-around text-center">
 <%= link_to "My Book Shelf", items_path, class:"text-white" %>
  <%= link_to 'Uncatalogued', uncategorized_items_path, class: "text-white" %>
 <%= link_to "Catalogued", groups_path, class:"text-white" %>
</div>


</header>

app/views/home/_profile.html.erb
<div class="home-body">
<div class="container">
<div class="profile-img-cont text-center pt-4">
<div class="profile-picture mx-auto border border-2 rounded">
<%= image_tag @user.image_url.to_s, class:"img-fluid profile-picture p-1" %>

</div>
<small class="fs-2"><%= @user.username %></small>

</div>

<ul class="nav d-flex flex-column">
    <li class="nav-item pb-2 d-flex"> 
        <i class="bi bi-journal-check fs-1 align-self-center "></i>
        <span class="d-inline-block w-75 px-3 pt-3 align-self-center">
        <%= link_to "My Book Shelf", items_path, class:"text-white" %>
        <p class=" border-bottom pt-2"></p>
        </span>
    </li>
    <li class="nav-item pb-2 d-flex"> 
        <i class="bi bi-journal-text fs-1 align-self-center "></i>
        <span class="d-inline-block w-75 px-3 pt-3 align-self-center">
        <a href="" class="text-white ">  Uncatalogued Books </a>
        <p class=" border-bottom pt-2"></p>
        </span>
    </li>
    <li class="nav-item pb-2 d-flex"> 
        <i class="bi bi-journal fs-1 align-self-center "></i>
        <span class="d-inline-block w-75 px-3 pt-3 align-self-center">
        <%= link_to "Catalogued Books", groups_path, class:"text-white" %>
        <a href="" class="text-white ">  </a>
        <p class=" border-bottom pt-2"></p>
        </span>
    </li>
    <li class="nav-item pb-2 d-flex"> 
        <i class="bi bi-person-fill fs-1 align-self-center "></i>
        <span class="d-inline-block w-75 px-3 pt-3 align-self-center">
        <%= link_to "Edit Profile", edit_user_registration_path, class:"text-white" %>
        <p class=" border-bottom pt-2"></p>
        </span>
    </li>
    <li class="nav-item pb-2 d-flex"> 
        <i class="bi bi-box-arrow-left fs-1 align-self-center "></i>
        <span class="d-inline-block w-75 px-3 pt-3 align-self-center">
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class:" btn p-0 m-0 text-white" %>
         <p class=" border-bottom pt-2"></p>
        </span>
    </li>
</ul>






</div>
</div>

app/views/home/index.html.erb
<% if current_user %>
    <%= render 'profile' %>
<% end %>

app/views/items/_form.html.erb
<div class="container text-center mt-5">
<h3 class="my-5"> New Item   </h3>
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class:"form-label" %>
    <%= form.text_field :name, required: true, class:"form-control" %>
  </div>

  <div class="mt-4">
    <%= form.label :amount, style: "display: block", class:"form-label" %>
    <%= form.number_field :amount, required: true, class:"form-control" %>
  </div>

  <div class= "control_group mt-2 ">
    <%= form.label :group, class: "control-group my-3"%>
    <div >

    <%= collection_select( :item, :group_id, Group.order(:name), :id, :name, {:prompt => 'Choose a Category'}, { :multiple => false } ) %>
   
    </div>
  </div>

  <div>
    <%= form.number_field :user_id, id: :item_user_id, value: current_user.id, type: :hidden, class:"form-control" %>
  </div>

  <div class="my-3">
    <%= form.submit "Add Item", required: true, class:"btn btn-custom p-3 mt-3"  %>
  </div>
<% end %>
</div>

app/views/items/index.html.erb
<%= render 'header/nav' %>
<div class="container my-3 ">
<h1  class="text-center my-3">List of Books </h1>


<div id="items" class="mb-5 pb-5">
<% running_total = 0 %>
  <% @items.each do |item| %>
    <div class="card mb-4">
      <div class="card-body row align-items-center"">
        <div class="d-flex col-9 ">
        <% if item.group_id %>
        <%= image_tag item.group.icon_url, class:"img-fluid p-1 border border-2 item-icon" %>
        <% else %>
                  <img src="https://via.placeholder.com/100" alt="icon" class="border border-1 item-icon "> 
        <% end %>
          <p class="px-3 p-md-3 align-self-center">
          <strong class="d-block mb-4 mb-md-5 capitalize"> <%= item.name %> </strong>
          <strong class="d-block"><%= item.created_at.strftime("%d %b %Y") %> </strong>
          
          </p>
        </div>

        <div class="col-3 text-end">
          <p class="card-text  mb-4"><%= number_to_currency(item.amount) %></p>
          <%= button_to "Delete", item, method: :delete, class:"btn btn-primary" %>
        </div>
        <% running_total = running_total + (item.amount) %>
      </div>
    </div>
  <% end %> 
     <hr />
    <hr />
    <h3>Total Amount: <%= number_to_currency(running_total) %></h3>
   <h3>Numers of Item: <%= @items.count %></h3>
</div>


<div class="text-center fixed-bottom pt-2 pb-3 bg-light">
<%= link_to "New Item", new_item_path, class:"btn btn-custom w-75 fs-3 mx-auto text-white" %>
</div>
</div>

app/views/items/new.html.erb
<%= render 'header/nav', class:"" %>

<%= render "form", item: @item %>

<br>

<div class="text-center">
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/uncategorized.html.erb
<%= render 'header/nav' %>
<div class="container my-3 ">
<h1  class="text-center my-3">Uncatalogued Books </h1>


<div id="items" class="mb-5 pb-5">
<% running_total = 0 %>
  <% @uncategorized.each do |uncategorized| %>
    <div class="card mb-4">
      <div class="card-body row align-items-center"">
        <div class="d-flex col-9 ">
          <img src="https://via.placeholder.com/100" alt="icon" class="border border-1 item-icon "> 
          <p class="px-3 p-md-3 align-self-center">
          <strong class="d-block mb-4 mb-md-5 capitalize"> <%= uncategorized.name %> </strong>
          <strong class="d-block"><%= uncategorized.created_at.strftime("%d %b %Y") %> </strong>
          
          </p>
        </div>

        <div class="col-3 text-end">
          <p class="card-text  mb-4"><%= number_to_currency(uncategorized.amount) %></p>
          <%= button_to "Delete", uncategorized, method: :delete, class:"btn btn-primary" %>
        </div>
        <% running_total = running_total + (uncategorized.amount) %>
      </div>
    </div>
  <% end %> 
     <hr />
    <hr />
    <h3>Total Amount: <%= number_to_currency(running_total) %></h3>
   <h3>Numers of Item: <%= @uncategorized.count %></h3>
</div>


<div class="text-center fixed-bottom pt-2 pb-3 bg-light">
<%= link_to "New Item", new_item_path, class:"btn btn-custom w-75 fs-3 mx-auto text-white" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <% if notice %>
        <p class="notice alert-success p-2 m-0"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-warning p-2 m-0"><%= alert %></p>
      <% end %>
    <%= yield %>

</body>
</html>